server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 192.168.146.132
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
mybatis-plus:
  type-aliases-package: com.example.personalblogsystem.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl